version: "3.3"
services:
  slidev:
    image: "agentzhao/slidev:latest"
    container_name: slidev
    build:
      context: ./
    volumes:
      - .:/app
      - /app/node_modules #empty mount to not overwrite node_modules
      - $PWD/dist:/app/dist
    ports:
      - "3030:3030"
